version: '3'
services:
  client:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - '80:80'
  api:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    ports:
      - '4000:4000'
    depends_on:
      - "mongodb"
    command: ["./wait-for-it.sh", "mongodb:4000", "--", "npm", "run", "start"]
  mongodb:
    build:
      dockerfile: Dockerfile.dev
      context: ./mongodb
    environment:
        - MONGO_INITDB_DATABASE=indego
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - '27017:27017'
